name: Deploy Backend Venta to AWS

on:
  push:
    branches: [ deploy ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar Código del Repositorio
      uses: actions/checkout@v3

    - name: Iniciar Sesión en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Construir y Publicar Imagen de Venta
      # 🌟 IMPORTANTE: Le decimos que compile usando la subcarpeta de venta
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/back-venta:latest ./back_venta
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/back-venta:latest

    - name: Desplegar en AWS EC2 vía SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_IP }}
        username: ec2-user
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /home/ec2-user/back_venta || mkdir -p /home/ec2-user/back_venta
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/back-venta:latest
          sudo docker stop contenedor-back-venta || true
          sudo docker rm contenedor-back-venta || true
          sudo docker run -d -p 5001:5001 --name contenedor-back-venta --restart always ${{ secrets.DOCKERHUB_USERNAME }}/back-venta:latest