name: Deploy Backend Venta to AWS

on:
  push:
    branches: [ deploy ]

jobs:
  build-push-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR (runner)
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build imagen Backend y push a ECR
      run: |
        # Buscar el Dockerfile dinámicamente sin importar las mayúsculas o la ruta exacta
        DOCKERFILE_PATH=$(find . -iname "Dockerfile" | grep -i "venta" | head -n 1)
        
        if [ -z "$DOCKERFILE_PATH" ]; then 
          echo "Error: No se encontró ningún Dockerfile para Venta"; 
          exit 1; 
        fi
        
        TARGET_DIR=$(dirname "$DOCKERFILE_PATH")
        echo "Carpeta de Venta encontrada: $TARGET_DIR"
        
        cd "$TARGET_DIR"
        docker build -t back-venta .
        docker tag back-venta:latest 558314634857.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/back-venta:latest
        docker push 558314634857.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/back-venta:latest

    - name: Desplegar Backend vía SSM
      run: |
        aws ssm send-command \
          --instance-ids i-035c8a0d0ca2a6be6 \
          --document-name "AWS-RunShellScript" \
          --comment "Actualizar back-venta desde ECR" \
          --parameters '{"commands":[
            "set -e",
            "aws ecr get-login-password --region '${{ secrets.AWS_REGION }}' | docker login --username AWS --password-stdin 558314634857.dkr.ecr.'${{ secrets.AWS_REGION }}'.amazonaws.com",
            "docker pull 558314634857.dkr.ecr.'${{ secrets.AWS_REGION }}'.amazonaws.com/back-venta:latest",
            "docker stop contenedor-back-venta || true",
            "docker rm contenedor-back-venta || true",
            "docker run -d --name contenedor-back-venta -p 5001:5001 558314634857.dkr.ecr.'${{ secrets.AWS_REGION }}'.amazonaws.com/back-venta:latest"
          ]}' \
          --output text