name: Deploy Backend Venta to AWS

on:
  push:
    branches: [ deploy ]

jobs:
  build-push-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login en Amazon ECR (runner)
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build imagen Backend y push a ECR
      run: |
        cd ./back-Ventas_SpringBoot/Springboot-API-REST-VENTAS
        docker build -t back-venta .
        docker tag back-venta:latest 558314634857.dkr.ecr.us-east-1.amazonaws.com/back-venta:latest
        docker push 558314634857.dkr.ecr.us-east-1.amazonaws.com/back-venta:latest

    - name: Desplegar Backend vía SSM
      run: |
        aws ssm send-command \
          --instance-ids PON_AQUI_EL_ID_DE_TU_INSTANCIA_EC2 \
          --document-name "AWS-RunShellScript" \
          --comment "Actualizar back-venta desde ECR" \
          --parameters '{"commands":[
            "set -e",
            "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 558314634857.dkr.ecr.us-east-1.amazonaws.com",
            "docker pull 558314634857.dkr.ecr.us-east-1.amazonaws.com/back-venta:latest",
            "docker stop contenedor-back-venta || true",
            "docker rm contenedor-back-venta || true",
            "docker run -d --name contenedor-back-venta -p 5001:5001 558314634857.dkr.ecr.us-east-1.amazonaws.com/back-venta:latest"
          ]}' \
          --output text