name: Deploy Backend Despacho to AWS

on:
  push:
    branches: [ deploy ]

jobs:
  build-push-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR (runner)
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build imagen Backend y push a ECR
      run: |
        TARGET_DIR=$(find . -type d -name "Springboot-API-REST-DESPACHO" -print -quit)
        if [ -z "$TARGET_DIR" ]; then echo "Error: Carpeta del proyecto no encontrada"; exit 1; fi
        cd "$TARGET_DIR"
        docker build -t back-despacho .
        docker tag back-despacho:latest 558314634857.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/back-despacho:latest
        docker push 558314634857.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/back-despacho:latest

    - name: Desplegar Backend vía SSM
      run: |
        aws ssm send-command \
          --instance-ids i-035c8a0d0ca2a6be6 \
          --document-name "AWS-RunShellScript" \
          --comment "Actualizar back-despacho desde ECR" \
          --parameters '{"commands":[
            "set -e",
            "aws ecr get-login-password --region '${{ secrets.AWS_REGION }}' | docker login --username AWS --password-stdin 558314634857.dkr.ecr.'${{ secrets.AWS_REGION }}'.amazonaws.com",
            "docker pull 558314634857.dkr.ecr.'${{ secrets.AWS_REGION }}'.amazonaws.com/back-despacho:latest",
            "docker stop contenedor-back-despacho || true",
            "docker rm contenedor-back-despacho || true",
            "docker run -d --name contenedor-back-despacho -p 5000:5000 558314634857.dkr.ecr.'${{ secrets.AWS_REGION }}'.amazonaws.com/back-despacho:latest"
          ]}' \
          --output text
          